name: Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Reusable workflow
        uses: ryansonshine/ryansonshine/.github/workflows/pr.yml@main
