name: Release

on:
  push:
    branches:
      - main

jobs:
  setup-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

  release:
    needs: setup-and-release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ryansonshine/ryansonshine/.github/workflows/release.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
