name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Reusable workflow
        uses: ryansonshine/ryansonshine/.github/workflows/release.yml@main
        secrets:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
